apiVersion: apps/v1
kind: Deployment
metadata:
  name: kbtvuelo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kbtvuelo
  template:
    metadata:
      labels:
        app: kbtvuelo
    spec:
      containers:
        - name: kbtvuelo-container
          image: kbtvuelo-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/kbtvuelo
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: root
